---
title: "Presentation d'un métier de consultant"
# subtitle: "with xaringan"
author: "Camille Bonamy"
institute: "Next Decision"
date: "2019/10/11" # (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false

---
```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

# Plan

* Introduction

* Qu'est ce qu'un consultant ?

* Les emplois autour de la Data Science

* Quelques références fonctionnelles

* La question du coût du travail

* Bonus

---
class: inverse, center, middle

# Introduction

---

## Qui ?

Camille Bonamy

* Issu de la promo 2017-2018 Master IS

* Stage de fin d'étude pour Next Decision chez un client : AS24, filière du groupe Total sur le thème de la détection de fraudes

* En poste de Data Scientist chez Next Decision

--

## Quoi ?

Les missions que j'ai effectué ont pour thème :

- la qualité des données
- la visualisation des données (reporting et app shiny) et des indicateurs
- la création d'indicateurs (e.g par réduction des dimensions ou test de significativité)
- la modélisation et la prévision (retard de livraison, qualité de produit, étude des commandes)

---

class: inverse, center, middle

# Qu'est ce qu'un consultant ?

---

## Définition

Un consultant est un prestataire de services en conseil. Les consultants sont souvent regroupés au sein de sociétés de conseil, ou bien interviennent de façon indépendante. Il dispose d'un savoir-faire avéré dans un domaine bien précis sans pour autant être spécialiste. [https://fr.wikipedia.org/wiki/Consultant]

--
## Mon Entreprise

__Next Decision__ est un "Cabinet d'experts en Informatique Décisionnelle & Big Data, Master Data Management (MDM), et Elaboration Budgétaire".

* Les consultants sont donc amené à se déplacer chez les clients (pour recueillir le besoin, travailler avec les métiers, faire des présentations, ...) sur une période donnée. 

* Le travail à distance en agence et le télé-travail sont également utilisés.

* Un consultant expérimente ainsi le fonctionnement de différentes entreprises et travail sur des problématiques variées.

---

class: inverse, center, middle

# Les emplois autour de la Data Science

---

## Bestiaire non exhaustif

Un projet peut être mené par  

* un Data Scientist
* un Data Analyst
* un Data Engineer
* un Data Architect (en support)

Ceux-ci interagissent avec :

le support

* IT
  + BI (Business Intelligence)
  + "Infra" (Infrastructure)
  + Réseau
  + ...

pour le compte d'utilisateurs finaux

* Les "métiers" : marketing, commerciaux, logistiques, production, ...

---

class: inverse, center, middle

# Quelques références fonctionnelles R-istes et +

---

__De manière général après 5 mn de blocage__
* https://stackoverflow.com

__Pour garder une trace, diffuser et rendre sa recherche reproductible__
* apprendre : https://happygitwithr.com/
* utiliser : Github, Gitlab, ...

__Pour manipuler les données, se connecter à des bases, sites...__
* https://www.tidyverse.org/

__ML et +__
* https://r4ds.had.co.nz/introduction.html  (pour apprendre)
* https://www.rfordatasci.com/              (pour apprendre)

* http://topepo.github.io/caret/index.html
* https://mlr.mlr-org.com/

__Des viz pour convaincre et persuader__
* http://www.ggplot2-exts.org/gallery/
* https://github.com/rfordatascience/tidytuesday

---

class: inverse, center, middle

# La question du coût du travail

---

__Moyenne Nantaise supposée pour un développeur consultant__

--
* 28k€ brut annuel
* Des écarts importants selon le secteur, le poste et la taille de l'entreprise

__Paris__

* Coût de la vie estimé (INSEE) de 20% à 25% plus cher -->> si linéaire 33.6k€ - 35k€ brut
--

## Take home message

* Les missions que vous effectuerez légitimerons votre status (expertise Data Science, Viz, Base de donnée et Big Data ?)

* Trouver une entreprise avec une équipe en place avec de l'expérience peut être un plus

* Une petite entreprise à d'avantage de chances de vous donner plus de responsabilités


---

class: inverse, center, middle

# Merci pour votre attention

### Présentation créée avec xaringan : https://github.com/yihui/xaringan

---

class: inverse, center, middle

# Bonus

---

__De l'open source français__
* http://larmarange.github.io/analyse-R/ (apprendre en français)
* https://github.com/dreamRs/esquisse ; https://github.com/ThinkR-open/golem 

__Comment créer un package R en ~ 2 mn__
* https://thinkr.fr/creer-package-r-quelques-minutes/

__Comment créer un module Python__
* https://stackabuse.com/creating-and-importing-modules-in-python/

__Docker pour exporter vos travaux et 'mettre en production'__
* https://colinfay.me/docker-r-reproducibility/

__RStudio et +__
* https://www.youtube.com/watch?v=bmaigtpKyiM (tuto tidyverse)
* https://rstudio.cloud/ et https://rstudio.com/products/shinyapps/ (connect pour deployer son app shiny)

__Un morceau de communauté R en France__
* https://github.com/frrrenchies/frrrenchies (annuaire)
* https://kutt.it/rgrrr                      (slack)

---

class: inverse, center, middle

# Bonus #2

---

__Questions d'entretien de stage :__

* Dans quel package se trouve la fonction __lm__ ?

* Quel est votre package préféré pour entraîner des modèles ?

* Avez vous effectué des projets ? Sont-ils sur git ?

* Avez vous un profil Kaggle ?

* Avez vous déjà participé à un challenge data ?

* Avez vous travaillé avec des données issues de problématiques réelles ? (Comprendre données non propre)

* Quels sont les étapes pour mener un projet de data science ?

* Pouvez vous expliquer en terme simple un algorithme de machine learning (type random forest)

Suivi de test (papier...) SQL, Python et R.